---
sidebar: sidebar 
permalink: automation/get-started-with-the-rest-api.html 
keywords: REST API 
summary: 'L"accès à l"API fournit une perspective avant de commencer à l"utiliser avec les processus de workflow plus complexes dans une configuration en direct.' 
---
= Commencez avec l'API REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez vous lancer rapidement à l'aide des outils ONTAP pour l'API REST VMware vSphere. L'accès à l'API fournit une perspective avant de commencer à l'utiliser avec les processus de workflow plus complexes dans une configuration en direct.



== Bonjour tout le monde

Vous pouvez exécuter une commande simple sur votre système pour commencer à utiliser les outils ONTAP pour l'API REST VMware vSphere et vérifier sa disponibilité.

.Avant de commencer
* Assurez-vous que l'utilitaire Curl est disponible sur votre système.
* Adresse IP ou nom d'hôte des outils ONTAP pour le serveur VMware vSphere
* Nom d'utilisateur et mot de passe pour un compte autorisé à accéder aux outils ONTAP pour l'API REST VMware vSphere.



NOTE: Si vos informations d'identification incluent des caractères spéciaux, vous devez les formater de manière acceptable pour Curl, en fonction du shell que vous utilisez. Par exemple, vous pouvez insérer une barre oblique inverse avant chaque caractère spécial ou envelopper la chaîne entière `username:password` entre guillemets simples.

.Étape
Sur l'interface de ligne de commande, exécutez les commandes suivantes pour récupérer les informations du plug-in :

`curl -X GET -u username:password -k "\https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Exemple :

`curl -X GET -u admin:password -k "'\https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
