---
permalink: automation/how-to-access-rest-api.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 'Vous pouvez accéder ONTAP à l"API REST de plusieurs façons.' 
---
= Comment accéder aux outils ONTAP pour l'API REST VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez accéder ONTAP à l'API REST de plusieurs façons.



== Considérations réseau

Vous pouvez vous connecter à l'API REST via les interfaces suivantes :

* LIF Cluster-management
* FRV de gestion des nœuds
* LIF de gestion SVM


La LIF que vous choisissez d'utiliser doit être configurée pour prendre en charge le protocole de gestion HTTPS. De plus, la configuration du pare-feu de votre réseau doit autoriser le trafic HTTPS.


NOTE: Vous devez toujours utiliser une LIF de cluster management. La charge sera ainsi équilibrée entre les requêtes d'API sur tous les nœuds et évitez les nœuds hors ligne ou qui rencontrent des problèmes de connectivité. Si plusieurs LIF de cluster management sont configurées, elles sont toutes équivalentes en ce qui concerne l'accès à l'API REST.



== Page de documentation en ligne des outils ONTAP pour l'API VMware vSphere

Vous pouvez accéder au swagger à partir du lien hypertexte figurant sur la page de support du plug-in NetApp ONTAP Tools for VMware vSphere.

Le format de l'URL utilisé pour accéder à la page de documentation de la version la plus récente de l'API est :

`https://<loadbalancer_ip_address>/docs/api'



== Logiciels et outils personnalisés

Vous pouvez accéder aux outils ONTAP pour l'API VMware vSphere à l'aide de plusieurs langages et outils de programmation. Il s'agit généralement de Python, Java, Curl et PowerShell. Un programme, un script ou un outil qui utilise l'API agit comme un client de services Web REST. L'utilisation d'un langage de programmation permet de mieux comprendre l'API et offre la possibilité d'automatiser les outils ONTAP pour l'administration de VMware vSphere.

Le format de l'URL de base utilisé pour accéder directement à la version la plus récente de l'API est :

`https://<loadbalancer_ip_address>/api'

Pour accéder à une version API spécifique où plusieurs versions sont prises en charge, le format de l'URL est le suivant :

`https://<loadbalancer_ip_address>/api/v1'
