---
permalink: automation/mount-unmount-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 'Vous pouvez monter un datastore VMware Virtual volumes (vVols) sur un ou plusieurs hôtes supplémentaires pour fournir un accès au stockage à des hôtes supplémentaires. Vous pouvez démonter le datastore vVols à l"aide d"API.' 
---
= Monter et démonter un datastore vVols
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez monter un datastore VMware Virtual volumes (vVols) sur un ou plusieurs hôtes supplémentaires pour fournir un accès au stockage à des hôtes supplémentaires. Vous pouvez démonter le datastore vVols à l'aide d'API.

Utilisez l'API suivante pour monter ou démonter un datastore vVols. Vous devez transmettre x-auth pour l'API. Vous pouvez générer cette x-auth à partir de la nouvelle API ajoutée sous Auth dans swagger.

[listing]
----
/virtualization/api/v1/auth/vcenter-login
----
[listing]
----
PATCH
/virtualization/api/v1/vcenters/{vcguid}/vvols/datastores/{moref}/hosts
----
Exploitez le volume de données vVol depuis vCenter.

Corps de la demande

[listing]
----
{
  "operation": "mount",
  "morefs": [
    "host-7044"
  ],
}
----
Exemples : * montage sur un hôte supplémentaire

Utilisez l'API suivante pour effectuer un montage sur un hôte supplémentaire :

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "mount",
      "morefs": ["host-13"],
     }
----
* Démonter sur un hôte supplémentaire


Utilisez l'API suivante pour procéder au démontage sur un hôte supplémentaire :

[listing]
----
/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores/datastore-24/hosts

     Request Body
     {
      "operation": "unmount",
      "morefs": ["host-13"],
     }
----