---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez enregistrer et annuler l"enregistrement du fournisseur VASA auprès d"une instance vCenter Server à l"aide des outils ONTAP pour l"interface de plug-in à distance VMware vSphere.' 
---
= Enregistrez le fournisseur VASA avec une instance vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez enregistrer et annuler l'enregistrement du fournisseur VASA auprès d'une instance vCenter Server à l'aide des outils ONTAP pour l'interface de plug-in à distance VMware vSphere. La section Vasa Provider Settings affiche l'état d'enregistrement du VASA Provider pour le serveur vCenter sélectionné.

*Étapes*

. Connectez-vous au client vSphere à l'aide de `\https://vcenterip/ui`
. Dans la page des raccourcis, cliquez sur *NetApp ONTAP Tools* dans la section des modules externes.
. Sélectionnez *Paramètres* > *VASA Provider settings*. L'état d'enregistrement du fournisseur VASA s'affiche comme non enregistré.
. Cliquez sur le bouton *REGISTER* pour enregistrer le fournisseur VASA.
. Entrez un nom pour le fournisseur VASA et fournissez les informations d'identification de l'utilisateur de l'application ONTAP vSphere, puis cliquez sur *REGISTER*.
. Une fois l'enregistrement et l'actualisation de la page réussis, l'interface utilisateur affiche l'état, le nom et la version du fournisseur VASA enregistré. L'action de désinscription est activée.
. Pour désenregistrer le fournisseur VASA, effectuez les opérations suivantes :
+
.. Pour désenregistrer le fournisseur VASA, sélectionnez l'option *désenregistrer* au bas de l'écran.
.. Dans la page *Unregister VASA Provider*, vous pouvez voir le nom du fournisseur VASA. Dans cette page, indiquez les informations d'identification de l'utilisateur de l'application et cliquez sur *désinscrire*.



